"""Initializing Migration

Revision ID: 03aec28a6bb5
Revises: c2b6f886802e
Create Date: 2026-09-08 13:35:17.877960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aec28a6bb5'
down_revision: Union[str, Sequence[str], None] = 'c2b6f886802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('authorization_url', sa.String(length=500), nullable=True))
    op.add_column('payments', sa.Column('access_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'access_code')
    op.drop_column('payments', 'authorization_url')
    # ### end Alembic commands ###
