"""Replace Stripe fields with Paystack reference

Revision ID: 105a6c9b5857
Revises: b8860a7f64fc
Create Date: 2026-09-07 06:38:08.752229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105a6c9b5857'
down_revision: Union[str, Sequence[str], None] = 'b8860a7f64fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('paystack_reference', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['paystack_reference'])
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'paystack_reference')
    # ### end Alembic commands ###
