"""Add plan pricing and billing interval

Revision ID: 235f4929cec1
Revises: 105a6c9b5857
Create Date: 2026-09-07 07:22:46.726194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235f4929cec1'
down_revision: Union[str, Sequence[str], None] = '105a6c9b5857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "plans",
        sa.Column("description", sa.String(length=255), nullable=True)
    )

    op.add_column(
        "plans",
        sa.Column("price_kobo", sa.Integer(), nullable=True)
    )

    op.add_column(
        "plans",
        sa.Column("billing_interval", sa.String(length=20), nullable=True)
    )

    op.add_column(
        "plans",
        sa.Column("paystack_plan_code", sa.String(length=255), nullable=True)
    )

    op.create_unique_constraint(
        None,
        "plans",
        ["paystack_plan_code"]
    )

    op.execute("UPDATE plans SET price_kobo = 0")
    op.execute("UPDATE plans SET billing_interval = 'monthly'")

    op.alter_column(
        "plans",
        "price_kobo",
        nullable=False
    )

    op.alter_column(
        "plans",
        "billing_interval",
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='unique')
    op.drop_column('plans', 'paystack_plan_code')
    op.drop_column('plans', 'billing_interval')
    op.drop_column('plans', 'price_kobo')
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###
