"""add cost to usage events

Revision ID: cc40a6e4bebf
Revises: 83786c2e650f
Create Date: 2026-09-07 10:43:31.713267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc40a6e4bebf'
down_revision: Union[str, Sequence[str], None] = '83786c2e650f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_events', sa.Column('cost_micro_units', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'cost_micro_units')
    # ### end Alembic commands ###
